#cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_LONG_TIME_CASE=ON
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_LONG_TIME_CASE=OFF -DDEBUG_LEVEL_1=ON
#cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_LONG_TIME_CASE=OFF -DDEBUG_LEVEL_1=OFF
cmake --build build -j
